### ISSUE TITLE
XRd and Open vSwitch BMP full buffer

### ISSUE THREAD

**Issue by zwiy** [ios-xr/xrd-tools#17] opened 2023-01-19 09:41 UTC
We tried to connect multiple XRd containers via an OVS bridge and noticed that BMP doesn't work properly if `chcksum` is set on the containers' environment variables.

After BMP was enabled the buffer seemed to be full, although the buffer limit was not reached.
Also changing the `max-buffer-size` for all BMP servers didn't solve the problem.

Other protocols like ssh or streaming-telemetry didn't have any problems.

![xrd_bgp_show_process_statistics](https://user-images.githubusercontent.com/18480550/213405656-8f1851f0-6c4c-4e7e-9d8a-143e6a70fd92.png)
![xrd_bmp_summary](https://user-images.githubusercontent.com/18480550/213405676-4c962068-b71b-4ff7-a7d8-f12a82fa14fe.png)
![pcap](https://user-images.githubusercontent.com/18480550/213407733-703bc9e8-b5e5-4db6-b46f-305894dc0a92.png)

We could solve the problem by removing the `chcksum` setting on the interface:
```
XR_MGMT_INTERFACES: linux:eth0,xr_name=Mg0/RP0/CPU0/0
```

We thought this finding is maybe interesting also for others.

CC @severindellsperger

**Comment by jwwsmith** [comment] 2023-01-19 17:15
Hi, thanks for sharing your insight and findings.
It's great to hear what people are trying with XRd and that you've been able to successfully work through problems.

Let us know if there's anything else, or shall I close?

**Comment by zwiy** [comment] 2023-01-20 15:41
Hi @jwwsmith,
We don't know what exactly the problem is with `chcksum` in combination with OVS and BMP. Maybe you have some more insights to share with us?
Can be closed, thanks. It's working know.

**Comment by legaul-cisco** [comment] 2023-01-27 16:28
Hi @zwiy, thanks for reporting this issue.

We'd be interested to look into this a bit further when we get a chance since in theory having the `chksum` flag should never cause packet drops (which we assume must be the root of the problem here). It's possible this could be caused by the type of the packets, i.e. something to do with the BMP packets. The next step for us would be to reproduce this - would you be able to provide the XR config you're using?

It would also be good to get a better understanding of your setup, is this two XRd (XRd Control Plane?) instances connected over an OVS bridge? Are there any other hosts connected into the bridge sending packets to XRd?

**Comment by legaul-cisco** [comment] 2023-03-31 10:17
Hey @zwiy, it'd still be great to hear from you with any details of your setup to allow us to reproduce this. If not we'll close the issue for now, but please feel free to reply later on or open a new issue if you see something similar.

**Closed** 2023-04-24 11:08 UTC

**Comment by zwiy** [comment] 2023-04-24 11:28
Hey @legaul-cisco 
In the meantime we couldn't reproduce the behaviour since we changed our setup from OvS with q-in-q to OvS with OpenFlow.
But I can share our current setup with you: [XRd BMP Topology with OVS and OpenFlow](https://gist.github.com/zwiy/bfb069ce84c8335d803db0937f17b78d)
In this setup we couldn't reproduce the described behaviour above.
